import type {
  Client,
  User,
  Report,
  PaidMediaMetrics,
  GoogleAdsMetrics,
  MetaAdsMetrics,
  GA4Metrics,
  WhatsappMetrics,
  FunnelMetrics,
  FinancialMetrics,
  Diagnostic,
  ActionPlan,
} from "./types"

export const mockClients: Client[] = [
  {
    id: "c1",
    company_name: "Clínica Saúde Total",
    trade_name: "Saúde Total",
    segment: "Saúde / Clínica Médica",
    website: "https://saudetotal.com.br",
    instagram: "@clinicasaudetotal",
    main_objective: "Gerar leads para consultas e procedimentos estéticos",
    city: "São Paulo",
    state: "SP",
    status: "ativo",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
  },
  {
    id: "c2",
    company_name: "Academia Corpo em Forma",
    trade_name: "Corpo em Forma",
    segment: "Fitness / Academia",
    website: "https://corpoemforma.com.br",
    instagram: "@corpoemforma",
    main_objective: "Captação de novos alunos mensalistas",
    city: "Campinas",
    state: "SP",
    status: "ativo",
    created_at: "2024-02-10T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
  },
  {
    id: "c3",
    company_name: "Escritório Jurídico Mendes",
    trade_name: "Mendes Advogados",
    segment: "Jurídico",
    website: "https://mendesadvogados.com.br",
    instagram: "@mendesadvogados",
    main_objective: "Leads para consultoria jurídica trabalhista",
    city: "Rio de Janeiro",
    state: "RJ",
    status: "ativo",
    created_at: "2024-03-05T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
  },
]

export const mockReports: Report[] = [
  {
    id: "r1",
    client_id: "c1",
    report_type: "mensal",
    period_start: "2024-04-01",
    period_end: "2024-04-30",
    title: "Relatório Mensal – Abril 2024",
    executive_summary:
      "Abril foi um mês de crescimento consistente. O investimento em tráfego pago gerou 312 leads qualificados, com redução de 14% no custo por lead em relação a março. A campanha de procedimentos estéticos superou as metas estabelecidas.",
    main_highlight: "CPL reduziu 14% com volume 22% maior de leads.",
    main_warning: "Taxa de resposta comercial caiu para 68%, abaixo da meta de 80%.",
    next_steps:
      "1. Otimizar criativos do Meta Ads para conjunto estético\n2. Treinar equipe comercial para aumentar taxa de resposta\n3. Criar campanha Google Ads focada em palavras-chave de fundo de funil",
    created_by: "admin",
    created_at: "2024-05-01T10:00:00Z",
    updated_at: "2024-05-01T10:00:00Z",
  },
]

export const mockPaidMedia: PaidMediaMetrics[] = [
  {
    id: "pm1",
    report_id: "r1",
    client_id: "c1",
    channel: "Meta Ads",
    campaign_name: "Estética – Leads Frio",
    objective: "Lead Generation",
    spend: 4200,
    impressions: 180000,
    reach: 120000,
    frequency: 1.5,
    clicks: 3240,
    link_clicks: 2916,
    ctr: 1.8,
    cpc: 1.3,
    cpm: 23.33,
    leads: 198,
    conversions: 198,
    conversion_rate: 6.12,
    cpl: 21.21,
    cpa: 21.21,
    revenue: 18200,
    roas: 4.33,
    created_at: "2024-05-01T10:00:00Z",
  },
  {
    id: "pm2",
    report_id: "r1",
    client_id: "c1",
    channel: "Google Ads",
    campaign_name: "Consulta Médica – Search",
    objective: "Conversões",
    spend: 2800,
    impressions: 28000,
    clicks: 1120,
    link_clicks: 1008,
    ctr: 4.0,
    cpc: 2.5,
    cpm: 100,
    leads: 114,
    conversions: 114,
    conversion_rate: 10.18,
    cpl: 24.56,
    cpa: 24.56,
    revenue: 12400,
    roas: 4.43,
    created_at: "2024-05-01T10:00:00Z",
  },
]

export const mockGoogleAds: GoogleAdsMetrics[] = [
  {
    id: "ga1",
    report_id: "r1",
    client_id: "c1",
    campaign_name: "Consulta Médica – Search",
    ad_group_name: "Clínica Geral",
    keyword: "clínica médica são paulo",
    match_type: "Frase",
    spend: 980,
    impressions: 9800,
    clicks: 392,
    ctr: 4.0,
    cpc: 2.5,
    conversions: 42,
    cost_per_conversion: 23.33,
    conversion_rate: 10.71,
    impression_share: 72,
    top_impression_share: 58,
    absolute_top_impression_share: 31,
    lost_is_budget: 12,
    lost_is_rank: 16,
    quality_score: 8,
    status: "Escalar",
    recommendation: "Aumentar orçamento em 20% — perdendo impressão por budget.",
  },
  {
    id: "ga2",
    report_id: "r1",
    client_id: "c1",
    campaign_name: "Estética – Search",
    ad_group_name: "Procedimentos",
    keyword: "botox são paulo preço",
    match_type: "Exata",
    spend: 620,
    impressions: 4100,
    clicks: 185,
    ctr: 4.51,
    cpc: 3.35,
    conversions: 19,
    cost_per_conversion: 32.63,
    conversion_rate: 10.27,
    impression_share: 65,
    quality_score: 7,
    status: "Manter",
    recommendation: "Manter — boa taxa de conversão. Testar extensões de anúncio.",
  },
]

export const mockMetaAds: MetaAdsMetrics[] = [
  {
    id: "ma1",
    report_id: "r1",
    client_id: "c1",
    campaign_name: "Estética – Leads Frio",
    ad_set_name: "Lookalike 1% – SP",
    ad_name: "Video_Botox_Resultado",
    creative_name: "Video resultado botox 30s",
    audience: "Lookalike 1%",
    placement: "Feed + Reels",
    objective: "Lead Generation",
    spend: 1800,
    reach: 52000,
    impressions: 78000,
    frequency: 1.5,
    cpm: 23.08,
    clicks: 1404,
    link_clicks: 1264,
    ctr: 1.8,
    cpc: 1.28,
    leads: 87,
    conversations: 42,
    cost_per_lead: 20.69,
    hook_rate: 38,
    hold_rate: 22,
    thumbstop_rate: 41,
    status: "Escalar",
    recommendation: "Criativo vencedor. Aumentar orçamento em 30%.",
  },
  {
    id: "ma2",
    report_id: "r1",
    client_id: "c1",
    campaign_name: "Estética – Leads Frio",
    ad_set_name: "Interesse – Beleza SP",
    ad_name: "Carrossel_Procedimentos",
    creative_name: "Carrossel 5 procedimentos",
    audience: "Interesse Beleza",
    placement: "Feed",
    objective: "Lead Generation",
    spend: 1200,
    reach: 41000,
    impressions: 61500,
    frequency: 1.5,
    cpm: 19.51,
    clicks: 980,
    link_clicks: 882,
    ctr: 1.6,
    cpc: 1.22,
    leads: 61,
    cost_per_lead: 19.67,
    hook_rate: 28,
    hold_rate: 15,
    thumbstop_rate: 32,
    status: "Manter",
    recommendation: "Bom desempenho. Testar nova variação de copy.",
  },
]

export const mockGA4: GA4Metrics = {
  id: "g4-1",
  report_id: "r1",
  client_id: "c1",
  sessions: 5820,
  users: 4930,
  new_users: 4120,
  pageviews: 14200,
  engaged_sessions: 3492,
  engagement_rate: 60.0,
  average_engagement_time: 128,
  bounce_rate: 40.0,
  key_events: 312,
  conversions: 312,
  conversion_rate: 5.36,
  source: "google",
  medium: "cpc",
  device: "Mobile: 72% / Desktop: 24% / Tablet: 4%",
  landing_page: "/lp-estetica",
  whatsapp_clicks: 892,
  form_submits: 312,
  button_clicks: 1240,
}

export const mockWhatsapp: WhatsappMetrics = {
  id: "wa1",
  report_id: "r1",
  client_id: "c1",
  conversations_started: 234,
  messages_received: 1872,
  leads_answered: 191,
  leads_not_answered: 43,
  average_response_time: 18,
  response_rate: 81.6,
  qualified_leads: 142,
  unqualified_leads: 49,
  scheduled_appointments: 98,
  show_ups: 78,
  no_shows: 20,
  proposals_sent: 68,
  sales: 42,
  close_rate: 42.86,
  cost_per_conversation: 29.91,
  cost_per_appointment: 71.43,
  cost_per_sale: 166.67,
  lost_reasons: "Preço (38%), Sem urgência (28%), Não respondeu (22%), Outros (12%)",
}

export const mockFunnel: FunnelMetrics = {
  id: "fn1",
  report_id: "r1",
  client_id: "c1",
  impressions: 208000,
  clicks: 4360,
  site_visits: 5820,
  landing_page_views: 4942,
  leads: 312,
  whatsapp_conversations: 234,
  qualified_leads: 142,
  appointments: 98,
  show_ups: 78,
  proposals: 68,
  sales: 42,
  revenue: 30600,
  click_through_rate: 2.1,
  page_conversion_rate: 6.32,
  lead_to_appointment_rate: 31.41,
  appointment_to_sale_rate: 42.86,
  overall_conversion_rate: 0.02,
  main_bottleneck: "Conversão lead → agendamento está em 31%, abaixo do ideal de 45%.",
}

export const mockFinancial: FinancialMetrics = {
  id: "fi1",
  report_id: "r1",
  client_id: "c1",
  media_spend: 7000,
  management_fee: 2000,
  total_marketing_cost: 9000,
  revenue: 30600,
  gross_profit: 21600,
  average_ticket: 728.57,
  sales_count: 42,
  cac: 214.29,
  roas: 4.37,
  roi: 240,
  break_even_revenue: 9000,
  ltv: 1800,
  payback: 2.8,
  margin: 70.59,
}

export const mockDiagnostic: Diagnostic = {
  id: "d1",
  report_id: "r1",
  client_id: "c1",
  performance_status: "bom",
  what_improved:
    "Volume de leads cresceu 22%. O custo por lead caiu de R$ 24,80 para R$ 21,30. A campanha de estética no Meta Ads apresentou excelente desempenho, com CPL abaixo da meta.",
  what_worsened:
    "A taxa de resposta comercial caiu de 84% para 68%. Muitos leads chegaram fora do horário de atendimento e não receberam retorno em menos de 1 hora, o que reduziu a conversão.",
  main_problem:
    "O gargalo principal está no atendimento: a equipe comercial não consegue responder todos os leads dentro do tempo ideal de 10 minutos.",
  main_opportunity:
    "Implementar um robô de qualificação via WhatsApp para atender leads fora do horário comercial e agendar automaticamente. Isso pode aumentar a taxa de agendamento em até 40%.",
  traffic_diagnosis:
    "Tráfego pago performando bem. Meta Ads com CPL abaixo da meta e Google Ads com CTR acima da média do setor. Não há perda significativa de impressão por orçamento.",
  offer_diagnosis:
    "A oferta de consulta gratuita de avaliação está convertendo bem. Recomendamos manter e testar uma segunda versão com destaque no resultado antes/depois.",
  landing_page_diagnosis:
    "A landing page está com taxa de conversão de 6,3%, o que é acima da média do setor (3–5%). Mobile representa 72% do tráfego — verificar velocidade de carregamento mobile.",
  commercial_diagnosis:
    "Principal ponto de atenção: 18 minutos de tempo médio de resposta. Meta ideal é até 5 minutos. Taxa de resposta de 81,6% — existem 43 leads sem nenhuma resposta.",
  financial_diagnosis:
    "ROAS de 4,37x e ROI de 240% indicam campanha muito lucrativa. CAC de R$ 214 com ticket médio de R$ 728 é saudável. Margem de 70% permite escalar investimento.",
  conclusion:
    "Abril foi um mês positivo. O tráfego está otimizado e a oferta está funcionando. O maior risco está no atendimento comercial. Com a implementação da automação de WhatsApp e melhoria na velocidade de resposta, estimamos crescimento de 30–40% nas vendas no próximo mês.",
}

export const mockActionPlans: ActionPlan[] = [
  {
    id: "ap1",
    report_id: "r1",
    client_id: "c1",
    action: "Implementar bot de qualificação no WhatsApp para atendimento 24h",
    area: "WhatsApp",
    priority: "alta",
    deadline: "2024-05-10",
    responsible: "Equipe Comercial",
    status: "pendente",
    published_to_client: true,
    validated: true,
    comments: "Verificado e aprovado.",
  },
  {
    id: "ap2",
    report_id: "r1",
    client_id: "c1",
    action: "Escalar orçamento da campanha 'Video_Botox_Resultado' em 30%",
    area: "Meta Ads",
    priority: "alta",
    deadline: "2024-05-07",
    responsible: "Gestor de Tráfego",
    status: "em andamento",
    published_to_client: true,
    validated: true,
  },
  {
    id: "ap3",
    report_id: "r1",
    client_id: "c1",
    action: "Aumentar orçamento do grupo 'Clínica Geral' no Google Ads em 20%",
    area: "Google Ads",
    priority: "alta",
    deadline: "2024-05-07",
    responsible: "Gestor de Tráfego",
    status: "concluído",
    published_to_client: true,
    validated: true,
  },
  {
    id: "ap4",
    report_id: "r1",
    client_id: "c1",
    action: "Criar 3 novos criativos video para teste no Meta Ads – ângulo 'transformação'",
    area: "Criativos",
    priority: "média",
    deadline: "2024-05-15",
    responsible: "Equipe Criativa",
    status: "pendente",
    published_to_client: false,
  },
  {
    id: "ap5",
    report_id: "r1",
    client_id: "c1",
    action: "Treinar equipe de atendimento sobre SLA de resposta (meta: 5 minutos)",
    area: "Comercial",
    priority: "média",
    deadline: "2024-05-12",
    responsible: "Gestora Comercial",
    status: "pendente",
    published_to_client: false,
  },
  {
    id: "ap6",
    report_id: "r1",
    client_id: "c1",
    action: "Testar variação da landing page com destaque em resultado antes/depois",
    area: "Landing Page",
    priority: "média",
    deadline: "2024-05-20",
    responsible: "Dev / Designer",
    status: "pendente",
    published_to_client: false,
  },
  {
    id: "ap7",
    report_id: "r1",
    client_id: "c1",
    action: "Negativar termos irrelevantes identificados no Google Ads",
    area: "Google Ads",
    priority: "baixa",
    deadline: "2024-05-09",
    responsible: "Gestor de Tráfego",
    status: "concluído",
    published_to_client: false,
  },
  {
    id: "ap8",
    report_id: "r1",
    client_id: "c1",
    action: "Configurar evento de clique WhatsApp no GA4 para rastrear origem dos leads",
    area: "Rastreamento",
    priority: "baixa",
    deadline: "2024-05-14",
    responsible: "Gestor de Tráfego",
    status: "pendente",
    published_to_client: false,
  },
]

export const mockChartData = {
  leadsEvolution: [
    { month: "Jan", leads: 198, cpl: 28.4, spend: 5620 },
    { month: "Fev", leads: 221, cpl: 26.1, spend: 5770 },
    { month: "Mar", leads: 256, cpl: 24.8, spend: 6350 },
    { month: "Abr", leads: 312, cpl: 21.3, spend: 7000 },
  ],
  channelDistribution: [
    { channel: "Meta Ads", value: 198, color: "#3b82f6" },
    { channel: "Google Ads", value: 114, color: "#10b981" },
  ],
  weeklyLeads: [
    { week: "Sem 1", leads: 68, conversions: 9 },
    { week: "Sem 2", leads: 74, conversions: 11 },
    { week: "Sem 3", leads: 82, conversions: 12 },
    { week: "Sem 4", leads: 88, conversions: 10 },
  ],
  roasEvolution: [
    { month: "Jan", roas: 3.2, roi: 165 },
    { month: "Fev", roas: 3.6, roi: 190 },
    { month: "Mar", roas: 4.0, roi: 218 },
    { month: "Abr", roas: 4.37, roi: 240 },
  ],
}

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Admin Agência",
    email: "admin@agencia.com",
    role: "admin",
    created_at: "2024-01-01T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
    last_login: "2024-05-06T08:00:00Z",
  },
  {
    id: "u2",
    name: "Maria Santos",
    email: "maria@agencia.com",
    role: "member",
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
    last_login: "2024-05-05T16:00:00Z",
    assigned_clients: ["c1", "c2"],
  },
  {
    id: "u3",
    name: "João Ferreira",
    email: "joao@agencia.com",
    role: "member",
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
    last_login: "2024-05-04T14:00:00Z",
    assigned_clients: ["c3"],
  },
  {
    id: "u4",
    name: "Dr. Carlos Mendes",
    email: "carlos@saudetotal.com.br",
    role: "client",
    client_id: "c1",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
    last_login: "2024-05-03T10:00:00Z",
  },
  {
    id: "u5",
    name: "Ana Lima",
    email: "ana@corpoemforma.com.br",
    role: "client",
    client_id: "c2",
    created_at: "2024-02-15T10:00:00Z",
    updated_at: "2024-05-01T08:00:00Z",
    last_login: "2024-05-02T09:00:00Z",
  },
]
